source 'https://github.com/CocoaPods/Specs.git'

platform :ios ,'9.0'
use_frameworks!
target 'Toolbox' do
pod 'Alamofire', '~>4.4'
pod 'SwiftyJSON'
pod 'SSZipArchive', '~> 1.8.1'
pod 'SVProgressHUD', '~> 2.1.2'
pod 'LKDBHelper', '~> 2.4.2'

end
